### ISSUE TITLE
whats ur discord

### ISSUE THREAD

**Issue by prpldev** [fishzint/discord-boost-bot#1]
bot is erroring need some help lol

**Comment by fishzint** [comment]
> bot is erroring need some help lol

Nah

**Comment by prpldev** [comment]
man whats ur discord, i just need help with one file

**Comment by fishzint** [comment]
> man whats ur discord, i just need help with one file

All the files are there

**Comment by prpldev** [comment]
its saying capmonster-python aint

**Comment by prpldev** [comment]
the module aint

**Comment by fishzint** [comment]
bruh 😭😭 pipinstall capmonster_py then get a cap monster last reply 💀

**Comment by prpldev** [comment]
omg im so dumbbbb

**Comment by prpldev** [comment]
wait it still don't work

**Comment by prpldev** [comment]
man whats ur discord, its easier than this
